### ISSUE TITLE
Gather initial DCC group role info into registry definition

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#109]
The registry definition will include some small TSV files to deploy it with initial content. We should gather the initial state for some DCC groups so that it can be deployed with initial content. This will help mocking in dev CI environment but should also give us a reproducible deployment of the initial policies we want to deploy when we release this new feature.  (Subsequent groups will be added to production via administrator action on the registry UI.)

**Comment by ACharbonneau** [comment]
Linking some related issues: 
- Current globus groups: https://github.com/nih-cfde/training-and-engagement/issues/176#issuecomment-693535998
- Similar issue. Not sure if it should be superceded by this one, or if it's different: https://github.com/nih-cfde/cfde-deriva/issues/84

**Comment by karlcz** [comment]
The groups listed in that issue only seem to represent "reviewers".  Please help me gather and organize info that covers more specific roles for each DCC:
- data submitter: the one(s) who can submit a datapackage into the pipeline for that DCC and view existing submissions
- review decision: the one(s) who can view existing submissions and accept/reject a submission 
- read-only reviewers: anyone else who can (only) view existing submissions

If we expect to reuse a single group for more than one role, please tell me explicitly.  I think

**Comment by ACharbonneau** [comment]
Currently, I have use cases for data submitter and review decision, as you've described.

Data submitter would be anyone form a dcc who can submit
Review decision is a single person from each dcc who can approve

I suspect that in a venn diagram, the review decision group would be entirely or almost entirely inside the data submitter group, but that they still need to be distinct. 

Since we need each DCC to see only their own information, I think this means we need one Data submitter group per DCC, and one Review decision group per DCC.

Karl suggested that we likely want read only reviewers, and now that he's put it in my head, I think I have plausible use cases for it:

### Would want to be able to see submissions across all DCCs as read-only:
- Me, and others in the 'help DCCs get comfortable with the process' workgroup, who want to be able to help DCCs with a particular submission question or problem, without being able to personally change things. Having the ability to see what they see is going to be vital to helping them. It could work with write privileges, but I think it's safer to give help staff read-only.
- Haluk and Chris- The NIH Program Officers who oversee all the DCC CFDE awards in connection with our grant. They tend to like to personally track whether the DCCs are participating as expected, and I think given the option to check in on this, they would.
- Lora, our NIH Program Officer, who wants to check the coordination centers progress on the portal (getting submissions, processing them, etc). Honestly, I think that 99% of the time, Lora would just want this as a report rather than the ability to look herself.

### Would want to be able to see submissions for just one or two DCCs as read-only:
- NIH Program Officers for the main award of each DCC, who want to be able to see that their DCC is making progress on submissions. This is actually a specific thing that came out of Cia's UI interviews with POs earlier this year. They are always looking for ways they can see more up-to-date information than just periodic reporting.

Based on my understanding of Globus, if we were fulfilling these use cases, I think we would also need one read-only group per DCC, so any given PO for a DCCs main award would be put in just the group for their DCC, and that for e.g. Haluk or helpdesk would get access to all the DCCs by being added to each of those groups.

**Comment by karlcz** [comment]
For this issue, I am mostly interested in just the per-DCC roles that
would be represented as groups for which management has been (or
should be) delegated to the DCCs.  If necessary, I think we should
handle CFDE-wide access roles via another ticket with appropriate
review of existing groups and/or curation of new ones. This would
reflect CFDE-CC staff roles, other NIH oversight roles, etc.

Regardless, I was thinking that a DCC might have more people they want
involved in review/QA of their submission while only a small set
(perhaps one, as you suggest) would be able to enter the final DCC
decision.  I.e. have various staff check the content as a sort of
panel but then forward their concerns through the "approver" who
formally presents the combined DCC decision to CFDE-CC.

In all cases, I think it would be useful to break this down more than
"read-access" or "read-write" access.  I believe that the groups
should align more closely to staffing/HR roles where it can be clear
who would would manage turnover of membership in that group, and how
they would pragmatically know to do so.  We can then grant appropriate
access to members of these group(s) via our policies. The person
managing the group should be concerned with "what is this person's
function in my DCC" rather than "what technical access should I grant"
when dealing with day-to-day maintenance of the group membership
lists.

For example, in the long run it might be easier to manage groups
with conceptual roles like these per DCC:

- DCC _x_ ops/admin: a sysadmin/operations generalist
- DCC _x_ data submitter: informatician who produces C2M2 output
- DCC _x_ data SME: stakeholders who can view C2M2 presentations
- DCC _x_ CFDE decider: entrusted to inform CFDE of approvals
- DCC _x_ managers: people DCC needs to keep an eye on things
- DCC _x_ PI: maybe redundant, implies manager and admin as fallback?

One from your list that I am less sure of would be NIH program
officers scoped to only one or a few DCCs.  Who is the appropriate
managing party to curate these memberships?  Is it the DCC or
CFDE-CC or a joint responsibility...?

**Comment by ACharbonneau** [comment]
Conceptually I agree. We certainly haven't been giving the DCCs a list of access credentials to choose from, I've been giving them roles. Up till now, I've had 3 role options: the equivalent of `data submitter` and `CFDE decider`, and then a third one that is 'person at your DCC who adds/removes people from those two lists', so they would be the curator of the memberships. I was thinking we would offer a fourth role, something like 'data viewer'. 

I'm not opposed to adding other roles, but I have questions

It seems like:
 - managers: people DCC needs to keep an eye on things
 - SME: stakeholders who can view C2M2 presentations
 
would on our end both need read-only access, and so in my current scheme would be people the DCC designated as "Data Viewers". What is the benefit of making the DCC tell us why a given person needs to view data? Or to ask a different way, A DCC will be trying to map these roles to their staff, and each DCC uses (of course) different titles and roles for their people. So if I give them 6 roles to choose from, they're going to have a harmonization problem to solve, and want to know what the difference is between them to try to choose. What would I tell them? (as an aside, I have exactly this problem with contact info tracking for onboarding already, the role someone has in their organization and the role they are filling in their collaboration with the CFDE often have nothing to do with each other, so I have a manually harmonized contact list for each DCC that lists their roles *for us* as opposed to their roles at their job. Even PIs on the collaborative award are not necessarily the PI of the DCC.)

**Comment by karlcz** [comment]
I may have the minority opinion here, but I do not think we have
to force specific groups or group names on the DCCs. I admit I am not
sure how the onboarding process should work here as far as training.

What I think is that having group names well-aligned to the DCC concepts
of their staffing is important, so they actually can look at the lists
and realize they need to update them to track changes.

I am modeling a mapping layer in the registry where we can assign
CFDE role concepts to these registered groups.  So, ideally, one only
has to think hard about this mapping once in a while during onboarding
or DCC organizational upheaval, but otherwise they can just tend to
group member lists that make sense to them.

On your other point, I was imagining that down the road, an SME is
viewing currently-available-for-review C2M2 content.  A manager with
oversight might get to see other sorts of operational metadata
not significant to the SME who is looking at bioinformatics content.

**Comment by ACharbonneau** [comment]
Oh. I misinterpreted that they would have their own groups. If they are making up their own structure, my vision of endlessly fielding 'what does that mean' questions disappears. Onboarding being slightly more challenging is not a major concern for me. We expect to onboard at most 2-3 new DCCs a year.

**Comment by karlcz** [comment]
I added the initial "reviewer" groups to the mock content in the dev regisry.  I am not sure I mapped these correctly, but I assigned them to my read-only reviewer concept in the model.  (This is just for registering the group... the complementary policy to influence access control is not yet incorporated into the dev system.)

**Comment by karlcz** [comment]
I merged the 21 groups defined for 7 DCCs into the initial registry configuration.
