### ISSUE TITLE
Indicate horizontal scroll is an option 

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#142]
One of my testers pointed out that on pages like [File](https://app-staging.nih-cfde.org/chaise/recordset/#1/CFDE:file@sort(RID)) there are more columns off the right of the screen, but no indication of that, so the only way you can find out is accidentally scrolling it, or by resizing your window. 

I always look at it full screen on my dual monitor and so until 10 minutes ago I thought we were only displaying View, ID Namespace, Local Id, Filename, Project and Size In Bytes. I think if I've been looking at this thing for 9 months and had no idea there were more columns, then we need some kind of indicator :)

My normal view
![image](https://user-images.githubusercontent.com/1719360/108387748-e2190880-71db-11eb-8bbc-99f1a7bf3d7f.png)

Surprise extra columns:

![image](https://user-images.githubusercontent.com/1719360/108387816-f52bd880-71db-11eb-90c9-f1177e1c8ebd.png)

**Comment by karlcz** [comment]
Unfortunately, I think this is a pesky browser+platform specific issue where the vendor hides the scroll controls even though we've gone out of our way to make it scrollable.  @jrchudy  can you comment?

**Comment by ACharbonneau** [comment]
We see this on both:

OS (including version): macOS Big Sur v11.2.1
Browser (including version): Safari v14.0.3

and 

OS (including version): macOS Big Sur v11.2.1
Browser (including version): Chrome  v88.0.4324.182

**Comment by jrchudy** [comment]
We have a scroll bar for this but it's part of the "table container" and not the whole page (since we don't want the facet panel scrolling out of view. If you scroll the table down to the bottom, you will see paging controls and a scroll bar (depending on your browser setting).

Since this has become a hot topic while developing, I changed my browser to "always show scroll bars". On page load, I can see a scroll bar flash at the top of the table before the contents load. After the contents load, I still see that same scrollbar but at the very bottom of the table.

Sorry part of the page was cut off since I quickly drag captured while loading the table contents:
![image](https://user-images.githubusercontent.com/2932600/108424539-290ff980-71ee-11eb-8636-166444bbd6e8.png)

After everything is loaded and I scroll down:
![image](https://user-images.githubusercontent.com/2932600/108424566-35945200-71ee-11eb-913d-99e48570ee56.png)

**Comment by ACharbonneau** [comment]
Huh. So here's my settings:
![image](https://user-images.githubusercontent.com/1719360/108427568-5d45e300-720b-11eb-83ee-f569f92c41d6.png)

and my bottom:

![image](https://user-images.githubusercontent.com/1719360/108427728-9bdb9d80-720b-11eb-85ef-1b800f1f3374.png)

No scroll bar. If I do start scrolling I get a scroll bar, but not before, and not just from hovering like it does in most apps:


https://user-images.githubusercontent.com/1719360/108428518-aea2a200-720c-11eb-9a32-18eef924121d.mov

Setting my scrollbar to always *does* make me have a scrollbar tho. It's weird that it's behavior for when to show the scrollbar is different from other apps, but /shrug

**Comment by jrchudy** [comment]
From the discussions we had in the UX meeting today, we came to the conclusion that we can't force scrollbars to show for users since it's a decision made by the OS first and then the browser.

One way to mitigate having a wide table would be to reduce the amount of text in some of the headers ("Size in Bytes" comes to mind). Another is to move the most important information towards the beginning of the table so what is "not seen" on page load is less important information (like creation time).

**Comment by karlcz** [comment]
So, is this issue supposed to be closed or turned into some other actions?  Shouldn't just park here in this state...

**Comment by ACharbonneau** [comment]
I think it's "closed with nothing done"
