### ISSUE TITLE
Change what columns are included in export 

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#150]
I need to flesh this out more, but I want to change what information is included in the export from Deriva. Currently export from Biosample at least includes a bunch of columns that I don't even know what they are: RID, RCT, RMT, RCB, RMB 

Will update this issue with what I'd like the export to look like once I've explored it more.

**Comment by ACharbonneau** [comment]
Is there a mapping or explanation of what fields are exported into the various manifests? @karlcz or @jrchudy

**Comment by karlcz** [comment]
I think we have a default/heuristic export config right now, so it is probably dumping all the columns in the portal catalog's model which includes extra columns (and tables!). We probably need a custom config to dump only the core C2M2 concepts and ignore the extra bits introduced for the portal.
@ACharbonneau  As a general principle, would you agree that an export ought to look more like a subset of a C2M2 submission? If so, I think we could define a few layers of work here:
1. Custom configs for each table to export just the C2M2 columns of a dumped table.
2. Custom configs to limit what (if any?) connected tables get dumped for a given export focus.
3. A new export feature to dump the frictionless package definition corresponding to the dumped tabular data files
4. A new export feature to dump TSV rather than CSV files?

**Comment by ACharbonneau** [comment]
Yes. I think it should look more like a subset of a submission, but with some linked concepts included. Someone on my team is already building a list of what terms they were expecting to get from each table.

I think adding a tsv download option is fine, but I think most users will prefer csvs.

**Comment by karlcz** [comment]
We discovered that the CSV export button does not yet have the desired configurablity in Chaise.  We can customize the export menu to have a more appropriate "bag" export, but the CSV button will probablyl have to remain as-is until Chaise can add some new configuration options.

**Comment by ACharbonneau** [comment]
For now, I think it’s ok that there are extra columns, as long as the columns a user would need are there. Manifest tables are for putting into software not reading like a book. Eventually it would be nice to filter out truly useless columns, but right now, it's fine. 

My short term solution is that we provide documentation on what the columns are and what they mean, and we link it do the existing documentation. 

Amandas team is building a definition list of the existing columns, and will get it added to the portal docs

**Comment by karlcz** [comment]
A last-minute change also enabled these BDBAG exports from recordset.

**Comment by karlcz** [comment]
This issue is invalidated for QA by the db-scaling work... should we close it and move a later issue into the QA lane once the fixup work is completed?

**Comment by ACharbonneau** [comment]
yep, lets revisit after the scaling stuff is in place
