### ISSUE TITLE
Should DCCs have 'bulk edit' option?/Weird bulk edit behavior

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#153]
A tester with "Approver" status tried out the 'bulk edit' button and didn't understand it at all. It's hard to read the greyed out boxes, and theres very little in there that lets a user differentiate between submissions

For a DCC approver it looks like this:

![image](https://user-images.githubusercontent.com/1719360/108748868-16a70000-750d-11eb-8ece-370ec1fa7f78.png)

My gut feeling is that it would be really hard to usefully use that as a DCC, and might lead to weird behavior. For example, it just let me simultaneously set all the HMP data packages to "approved":

![image](https://user-images.githubusercontent.com/1719360/108749608-03e0fb00-750e-11eb-8703-0844757ac71a.png)

There is also a row at the top called "Record Number" and its not clear what it refers to. I have the option to click an X next to each one to "remove this record from the form" but I'm not sure if that just drops it from this view, or deletes it from the database:

![image](https://user-images.githubusercontent.com/1719360/108750129-aa2d0080-750e-11eb-912a-83aa000e5f72.png)

I checked, and it seems to just remove it from that screen, and only for that view (the columns come back if I refresh). So I'm not sure what the feature is supposed to be used for.

**Comment by karlcz** [comment]
It is a general feature of Chaise and you have mostly figured it out already...  the record number is just a position within that dynamically generated bulk-edit form.  The items to bulk edit were those found in the prior recordset search page from which you launched the edit.

The three (mostly) complementary ways to use bulk editing:
1. Use search criteria to get the set of things you want to edit, prior to launching the bulk edit tool
2. Using the remove button to prune the bulk edit form prior to submission (Submit only operates on what is in the final form at submit time)
3. Using the add or clone buttons to expand a bulk creation form.

The first method only applies to editing existing records you can find by search.  The last only applies to creating new records, e.g. for the CFDE-CC staff doing an onboarding exercise. The middle method applies to either.  You can drop sections you don't want to include in the final submission, whether because you didn't use narrow enough search critera prior to launching bulk edit or because you clicked add or clone too many times when building up a new record creation form...

**Comment by ACharbonneau** [comment]
Practically speaking, what do we do if someone simultaneously approves all of their active review catalogs?

**Comment by karlcz** [comment]
Not sure this will address your concerns, but:

The system-maintained failure or success value will also be a gating
property, so we really only need to worry about the case where
submissions have succeeded, would be rejected by the DCC anyway, but
they accidentally approved it?

There is also a place for CFDE-CC approval decisions in the registry,
and of course a need for oversight. So, I think we will have to have
some recurring workflow/monitoring for CFDE-CC staff to review
submissions which are approved by the DCC but not (yet) by the
CFDE-CC.  Here, we might notice inappropriate patterns and handle it
on a case by case basis?

Also, it seems to me that whether they use bulk edit or edit
individual items over multiple days, we will struggle with the human
oversight capacity if we are flooded with valid and approved
submissions.  But, I think we also said that this is in the category
of a "good problem" to explore and revisit later, rather than
over-engineer today.

If this bulk edit control remains a UX concern despite the above
context, I think we could explore adding an ACL to limit it to the
CFDE-CC staff groups.  I'm just not sure this will solve the other
social/resourcing issues we may face anyway.

**Comment by ACharbonneau** [comment]
Maybe we also need a "lets think about this later once we see how people break it" pipeline :) I'll move it to backlog for now.

**Comment by ACharbonneau** [comment]
closing until/unless this is an actual problem
