### ISSUE TITLE
Submission values don't match between 'Content Summary Charts' and 'Browse Submitted Data'

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#155]
Here I'm looking at Submission 5754e576-7545-11eb-9754-17335d75072b and it has 3 Projects in the summary.

![image](https://user-images.githubusercontent.com/1719360/108868123-e2424b00-75c3-11eb-9e41-42ff163b7917.png)

If I click on that 3 in the first row under Data Breakdown, it seemingly correctly loads a view of 3 projects:

![image](https://user-images.githubusercontent.com/1719360/108868834-9512a900-75c4-11eb-9c83-0b36d91368c9.png)

However if instead I click on the "Projects" button under "Browse Submitted Data" I get:
 
![image](https://user-images.githubusercontent.com/1719360/108868966-bb384900-75c4-11eb-8d59-b08e72339c38.png)

I think it has something to do with the Project from  3 in the first row under Data Breakdown being filtered to 'Super-Project: all records with value' and 'Parent Project: no value' but I can't find a way to replicate that search from the "Projects" page I go to from "Browse Submitted Data". "Browse Submitted Data" has a 'Super-Project' filter, but not a 'Parent Project' filter. They seem to be two different Project pages

**Comment by karlcz** [comment]
I think there are separate questions here to disentangle...
1. The lack of a `Parent Project` facet prevents you from reconstructing certain filters set by the charts page navigable links
2. Why is the chart page linking this very odd query mixing two facets?
3. Is there something wrong with the search result for this weird query?

The chaise page is showing the extra facet because it adjusts the UI to reveal the query state encoded in the URL (which has injected a search concept not included in the configured search UI for the project table).  We could change the UI configuration to include this extra facet to avoid that inconsistency.

I would have thought the chart really wants to link a query like this: https://app-staging.nih-cfde.org/chaise/recordset/#42/CFDE:project/*::facets::N4IghgdgJiBcDaoDOB7ArgJwMYFM6JAEsIAjdafEAYQDEARAURABoQAHDFAKxywBcA+sQEduvQVgAWhADZQBAMwDWOAJ4gAugF9modHzJoKCavSatRPfkIgjOVwWzAYcEQcrWadIAEoBJOk1WKRRCXCRKADYAVgAGL20gA@sort(RID)  i.e. show projects with the root-level DCC project as their parent (the direct "sub-projects" of the DCC).

I actually see some strange/buggy behavior from this Parent Project facet.  I have two tabs open where I have edited the facet controls after following the link from the charts page.  In both, I have just the "Parent Project: no value" choice selected.  One tab shows a single result (which I think is correct!  only one project lacks a parent and that is the root DCC project).  The other tab shows 4 results.

**Comment by karlcz** [comment]
I've reintroduced the Parent Project facet on the project page on dev.  This is done for release catalog 1 and in progress for each existing submission.  It would be good to poke at some fo these to see if this resolves some of the behavioral concerns.

Caveats:
1. It will not apply to future submissions until redeployed in action provider(s)
2. I am not sure the charts page is really using the appropriate filter to show what it intends (see above) to explicitly show a set of results who have the DCC as the parent project.

**Comment by jonathancrabtree** [comment]
@karlcz, the odd query was doubtless the result of my futzing around to find a generic query that would retrieve all projects immediately below the top-level one (i.e., the DCC). I probably began with an ERMrest query and then this was the result of trying to translate it into Chaise. It produced the correct result and I wasn't aware of the nuance of that facet not being included in the configured search UI (and maybe it was when I was first looking at this.)

I'm all for doing this in a less odd way, although it seems like your suggested replacement query contains the hard-coded RID for the HMP project in that particular catalog. That makes the non-odd replacement 2 queries, since for any given catalog and/or DCC you'd first have to query for the RID and then run the query you mentioned. Is there a non-odd way to do that with just one Chaise query (i.e., retrieve that layer of projects regardless of which catalog you're querying and what the DCCs are) or do I need to know the RID in advance? (By and large the dashboard-api endpoints don't return RIDs since they seemed like an internal implementation detail, but that could certainly be changed.)

**Comment by karlcz** [comment]
I included the RID in the dashboard_queries module specifically
because I anticipated its use in:

  .dimension('subproject', parent_project_RID='x')

and for this parent project filtering if navigating to the same
set in chaise.  So, I'd vote for exposing these through the dashboard
API as well and using them for this purpose.

**Comment by jonathancrabtree** [comment]
@ACharbonneau I'll fix the odd query issue that Karl mentioned although after I do so we'll still be left with the UX issue that the dcc_review page effectively defines "Project" as "immediate subproject of the DCC being reviewed", which raises the following questions:

1. Is this more useful to display than the total project count?
2. Should we show both total and top-level project counts on that page?
3. How can we make it clear on the summary page what we're reporting if we don't display both (i.e., rename it, add some hovertext)?

I'm counting top-level projects in dashboard because that's what the dashboard-api returns, but I don't remember where that particular definition of project crept into the informal specification (I don't think it's mentioned in the formal spec.) At least for HMP I think it is a useful thing to look at if you just want a high-level summary of what's in the database.

**Comment by ACharbonneau** [comment]
As I understand it, the model requires that every DCC have one overarching parent project that owns all the others, and then they can have any number of projects under that, each of which can have it's own sub-projects. 

So it forms a tree, with the one overarching parent as the trunk, some number projects as branches, and each of those projects can have any number of branches or tips inside them. 

At the moment, I think that HMP and the other data we have in the portal is only really using two levels of project: the main trunk project, and some number of branches that all directly belong to that project, but the model isn't constrained to only have two levels. I could have something like this:

![image](https://user-images.githubusercontent.com/1719360/109322957-ea4af680-7820-11eb-8f7c-8dfc75e02a35.png)

If the above is wrong, the rest of this will be wrong, and I will need someone to re-explain projects to me.

Assuming that's true, I'm not actually 100% sure which projects are 'parent' projects in the current view...is it just the branches that touch the trunk? or those branches + trunk? Or any project that has other projects inside of it?

At an arbitrary level of complexity, it gets really hard to tell someone what their hierarchy looks like in summary numbers. 

So, this might not be a particularly useful solution, but my proposal would be to display two numbers:

1. number of projects that have other projects inside them
2. number of projects that do not have other projects inside them

That probably won't reflect the way any given user thinks about their projects, but I don't know that we can actually do that. At least these two numbers would be definable.

I'm open to other, better suggestions tho.

**Comment by karlcz** [comment]
Yes, that's right that it is a hierarchy.  The definitions used by the chaise recordset UX for facets are:
- Super-Project: the set of ancestor nodes in the tree (parents, grand-parents...)
- Parent: the next higher node in the tree
So Project2 is the only parent of ProjectB in your figure.  But Main Project is a super-project of everything to the right of it in your figure.
Main Project is the only one without any Parent Project  nor Super-Project)

The dashboard queries module I designed includes a capability for getting summaries by "subproject" which is the inverse releationship of this Parent Project concept.  If you asked for stats by subproject, you specify a parent project (like Main Project) and it returns stats broken down by Project1, Project2, Project3.

The idea, when this was developed, was that a UX might eventually want to do incremental drill-down, so the user could select Project2 and then repeat this process getting stats for ProjectA and ProjectB, selecting ProjectA to see stats broken down by X and Y, etc.

**Comment by karlcz** [comment]
I echo what Jonathan said above, which is that expectations about exactly what should be displayed and counted are a tricky part of the UX design process.  Should the main project (dcc) be shown in the set of records when you click from the statistic?  If so, should it be counted in the displayed statistic too, or should the displayed result set have size N+1 compared to the count?

**Comment by karlcz** [comment]
FWIW, It would actually be difficult to show the set of results "everything in this DCC plus the DCC project itself" using the facets defined above. We don't support a search criteria like "has Parent Project foo OR is project foo".

What we'd actually need instead for Chaise is a slightly different facet concept "Super-Project (reflexive)" which includes the idea that any project is a super-project of itself.

**Comment by jonathancrabtree** [comment]
@ACharbonneau, as Karl said your description of the project hierarchy is accurate, although with respect to HMP specifically there are more than 2 levels (including the DCC project itself). This is why you saw 3 projects (just those on level 2) reported on the review page but 22 projects (those on levels 1-3) reported in Chaise without any facets defined.

@karlcz raises a good question about the inclusion of the root project(s) in displays and project counts. We're using the same DERIVA entity (project) to represent two real-world concepts from our conceptual data model: DCC and DCC project and so I'd argue that we should not include the top-level DCC [DERIVA] project when we list or display what a user would almost certainly understand to be projects _of_ a DCC. It's an implementation detail that should be hidden from the user but since they have more or less unfettered access to the underlying DERIVA instance through Chaise, we can't hide it completely.

**Comment by jonathancrabtree** [comment]
I've done the simple thing for now and changed the count and link to the total number of projects under the DCC, using a query like the one suggested above, but using the transitive project in project table to get everything. dashboard RC1 was tagged on Friday, so this will go into RC2.

**Comment by jonathancrabtree** [comment]
@karlcz I'm running into the following error trying to count all projects (using project_in_project_transitive) in some catalogs. It works fine in app-dev catalog 1, but on app-dev catalog 270, for example, I get this:

```
The request conflicts with the state of the server. No link found between tables :CFDE:project_root and :CFDE:project 409 Client Error: Conflict for url: [https://app-dev.nih-cfde.org/ermrest/catalog/270/aggregate/p_root:=CFDE:project_root/p:=CFDE:project/pipt:=(p_root:project_id_namespace,p_root:project_local_id)=(CFDE:project_in_project_transitive:leader_project_id_namespace,CFDE:project_in_project_transitive:leader_project_local_id)/num_projects:=cnt_d(pipt:member_project_local_id)] Details: b'409 Conflict\nThe request conflicts with the state of the server. No link found between tables :CFDE:project_root and :CFDE:project\n
```

This looks like an assertion about the schema rather than the data (i.e,. the fact that this particular catalog has exactly 1 project, the one that represents GTEx), but it's not completely clear to me.  Shouldn't the link between these tables exist regardless of whether there are any linked rows? Or is the schema somehow dependent on the data (or am I misunderstanding the error message)?

This may or may not be related, but in an earlier version of the code (the one deployed to app-dev right now) I actually get an authorization error when trying to query project_in_project in dev catalog 270 (despite being logged in and everything else seemingly working correctly):

```
The requested select access on :CFDE:project_in_project is forbidden.
401 Client Error: Unauthorized for url: [http://localhost/ermrest/catalog/270/attributegroup/children:=CFDE:project/pip1:=(children:id_namespace,children:local_id)=(CFDE:project_in_project:child_project_id_namespace,CFDE:project_in_project:child_project_local_id)/project:=right(pip1:parent_project_id_namespace,pip1:parent_project_local_id)=(CFDE:project:id_namespace,CFDE:project:local_id)/pip2:=(project:id_namespace,project:local_id)=(CFDE:project_in_project:child_project_id_namespace,CFDE:project_in_project:child_project_local_id)/parent:=(pip2:parent_project_id_namespace,pip2:parent_project_local_id)=(CFDE:project:id_namespace,CFDE:project:local_id)/parent:RID=62A/project:RID;project:id_namespace,project:local_id,project:name,project:abbreviation,project:description,num_subprojects:=cnt_d(children:RID)] Details: b'401 Unauthorized\nThe requested select access on :CFDE:project_in_project is forbidden.\n
```

That error you can see at https://app-dev.nih-cfde.org/dcc_review.html?catalogId=270 in the response to https://app-dev.nih-cfde.org/dashboard-api/dcc/GTEx/projects?catalogId=270

**Comment by karlcz** [comment]
On the topic of whether to count/include the root project, I think we
should also consider how this looks in a multi-DCC release catalog and
whether these concepts need to be aligned for that case?

Also, as I understand it, C2M2 allows files/biosamples/subjects to be
associated with a root project, so if we do not display it we might
end up "hiding" some DCC products that were not grouped under
additional subproject structure...?

**Comment by karlcz** [comment]
Regarding other query or permissions problems, let's use slack channels
for open-ended discussion or file new issues if there seem to be
bugs, OK?

I don't want to mix the UX issue reported by the test team with other
chatter we might have about backend integration, etc...

**Comment by karlcz** [comment]
I understood from the last call that this has been worked on and changes are on the brink of being deployed to test?  I'll move this to QA pipeline believing that is the case...

**Comment by karlcz** [comment]
I reviewed this topic w/ Arthur regarding C2M2 and want to emphasize that there is no requirement that subprojects be defined or that every entity belong to a sub-project when they are defined.  Does the revised UX address the scenario of file/subject/biosample entities being directly associated with the root-level dcc project, either as the sole config (e.g. for a "level 0" submission) or as a mixture with some entities being under subprojects and some not?

I think this should be part of the UX testcases @ACharbonneau

**Comment by jonathancrabtree** [comment]
@karlcz, yes on the brink of being deployed. For the time being I'm counting all [DERIVA] projects except for the DCC and using a Chaise query modified as you suggested. Also point taken on not cluttering up this issue with my query/auth problems, which should have gone elsewhere...

**Comment by abradyIGS** [comment]
[v1: agree with @karlcz -- the "minimal compliant C2M2 submission" examples we're advertising (formerly "Level 0") have no project subdivisions beyond "all this stuff belongs to this one top-level project, which represents the DCC" -- this isn't going to change until at least the first round of post-RFC-publication review]

[v2: @jonathancrabtree  oh, hey, great! i can go right back to not worrying about this :]

**Comment by jonathancrabtree** [comment]
WRT to level 0 submissions I'm not sure how it will behave. The revised UX doesn't assume that there are any subprojects although it will report "0 projects" and provide a Chaise link that lists none. I debated removing the link completely when there are no subprojects, but left it in on the basis that it alerts the DCC that there's something they're not submitting but could be. Debatable whether this is likely to be helpful or annoying.

**Comment by karlcz** [comment]
OK, sounds like this is in the realm of test team to include this no-subprojects scenario (and mixed scenario?) in their test data and see if they find further confusion/inconsistency to the UX or not?

**Comment by jonathancrabtree** [comment]
I wasn't around when the UX was first put together but it doesn't seem like support for level 0 datasets was necessarily considered and until https://github.com/nih-cfde/dashboard/issues/59 was filed didn't realize we had any. I would guess/hope that most of the UX will probably behave in a similar manner for level 0 datasets i.e., it doesn't outright crash or fail, but it's not super-useful because there's not a great deal to summarize. As I mentioned in that dashboard issue I'm not sure there's much we could do for a level 0 submission of Files other than perhaps display a histogram showing the file size distribution.

@karlcz , yes I'd say that's fair to say although now that I know we want nontrivial support for level 0 datasets I'll certainly try to test/develop using them as much as possible going forward.

**Comment by jonathancrabtree** [comment]
@ACharbonneau, a simple fix for this issue is also on staging now. The count should now be for "all projects of a DCC" (i.e., all projects below the DERIVA project that represents the DCC itself, but not including it) and the link should behave accordingly (and construct a query based on the DCC as the superproject.)

**Comment by ACharbonneau** [comment]
This is not working for me. In this screen:

![image](https://user-images.githubusercontent.com/1719360/109712667-52c20c80-7b6e-11eb-82f7-855ed1a1d29e.png)

if I click the `21`I get:

![image](https://user-images.githubusercontent.com/1719360/109712737-64a3af80-7b6e-11eb-9bb7-ddbbbb22de55.png)

and if I click the `3` I get:

![image](https://user-images.githubusercontent.com/1719360/109712779-72f1cb80-7b6e-11eb-8ce5-a83a9ea3afc4.png)

**Comment by jonathancrabtree** [comment]
@ACharbonneau can you shift-reload that first page to ensure you don't have any cached JavaScript files from the previous release? I don't see the behavior you've described and suspect this may be the reason. "Total toplevel_projects" is not something that should show up on that page (and it doesn't when I look at it.)

**Comment by jonathancrabtree** [comment]
@ACharbonneau I do see one problem on this page (apart from the apparent need for a cache-busting mechanism for releases.) There are three redundant links to the 21 projects and one of the three (the one under Data Breakdown) isn't correct - it looks like the RID of the DCC project isn't being set correctly so the Chaise link returns 0 projects instead of 21 projects. The other two "copies" of the link seem OK and since it's the lowest one on the page hopefully nobody will notice...

**Comment by ACharbonneau** [comment]
I dumped my cache and now I'm getting that behavior. I get 21 projects in a catalog from the `data total` and top right '21's, but zero from the `data breakdown` 21

**Comment by ACharbonneau** [comment]
I think this has been resolved except for the [caching](https://github.com/nih-cfde/dashboard/issues/64) and [project link error](https://github.com/nih-cfde/dashboard/issues/65) which now have their own issues
