### ISSUE TITLE
Portal model unique constraint cleanup

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#159]
These inconsistencies were found in manual review. Should fix here but also cross-check with C2M2 model specs...

Seem incorrect (see parenthetic note) or redundant (implicit reason for being listed without note):

- [x] collection.local_id (properly constrained in binary primary key)
- [ ] assay_type.id
- [ ] ncbi_taxonomy.id
- [ ] anatomy.id
- [ ] file_format.id
- [ ] data_type.id
- [ ] subject_role.id
- [ ] subject_granularity.id

Seem inconsistent/have questions:

- [ ] collection.name (would be nice, but means collisions cause errors?)
- [ ] assay_type.name (shouldn't we make these unique?)

Pinging @abradyIGS for C2M2 cross-checks...

**Comment by karlcz** [comment]
I removed the `collection.local_id` uniqueness as this seems the most significant mistake. The other points can probably be addressed in later releases after we have more time to discuss it...

**Comment by abradyIGS** [comment]
* agree with action so far; @karlcz is correct about removing the uniqueness constraint from `collection.local_id`.
   * at least in the [reference schema](https://github.com/nih-cfde/c2m2/blob/master/draft-C2M2_JSON_Schema_datapackage_specs/C2M2_Level_1.datapackage.json) currently supposed to be in use, there is a similarly inappropriate uniqueness constraint on `project.local_id`, which should be removed as well. I have taken both constraints out of the document linked above.

* as for whether or not CV term table `id` fields are explicitly marked unique or implicitly known to be unique due to a PK designation, i'm wholly agnostic as to final disposition, but my (weak) preference is that _if_ explicitly specifying this already-implied constraint doesn't cause or risk any processing errors, we should leave it in. despite its formal redundancy, it's still useful as a pedagogical crutch, and right now we need all of those we can find.

* `[CV term].name` should _not_ be unique, because i half expect we will be supporting the use of multiple concurrent ontologies in the near future (depending on decisions being made now in the ontology working group), and `name` clashes are expected and non-pathological in such a case

* follow-up for your consideration on `collection.name`: what i was trying to express with that constraint was that within a single submission (that is, within the space governed by a JSON Schema file bundled inside a submission bag), names of DCC-defined `collections` (i.e. datasets) shouldn't be replicated. I don't mean to block submissions from passing validation based on clashes with existing `collection.name` labels elsewhere that are disambiguated from the incoming labels by namespace attachments, but here we have a divergence of schematic context (which i don't know how to solve) between a single submission (a self-contained relational database described by the included schema) and the entire C2M2 production space (a merged collection of submissions, requiring [possibly solely in my mind] potentially looser constraints to accommodate such unions, like not enforcing a global uniqueness constraint on `collection.name`).
   * i would ideally like some way to express the requirement that a submission column should be unique _within the containing submission_, which I think is a well-defined and non-useless thing to want to do
   * given how severely we're now restricting `collection` usage -- basically limited to "only owning DCC can define a `collection` on a self-owned subset" -- temporarily, until we get some breathing room to explore the complexities of more general defining authority -- i'm not in a position to care one way or the other about this yet, but it'll be a lot harder to back out previously-validated clashing name labels (because some DCC decided to name all its collections "RNA-Seq Data" before being able to play with the actual ramifications of doing that) than it will to allow them after initially blocking such clashes.
   * advice and solutions are strongly solicited, although like I said this can be ignored until present deadline stresses are solved.
