### ISSUE TITLE
Data review link has wrong url

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#161]
When looking at the [home page](https://app-dev.nih-cfde.org/) or [dashboard page](https://app-dev.nih-cfde.org/dashboard.html), the "Data Review" link points to the [registry portal for submitted datapackages](https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:datapackage@sort(submission_time::desc::,RID)) instead of the [dcc review page](https://app-dev.nih-cfde.org/dcc_review.html) from the dashboard repository.

The links for the navbar are controlled by the default catalog that is set in `chaise-config.js` in the dashboard repo:
https://github.com/nih-cfde/dashboard/blob/master/chaise-config.js#L12

I could be wrong but noticed this during testing while reviewing the changes for epic2 in the dashboard repo.

**Comment by ACharbonneau** [comment]
I think current behavior is right, but I want to make sure I'm looking at the same thing. When I click here:
![image](https://user-images.githubusercontent.com/1719360/109313800-9cc98c00-7816-11eb-99bc-0c9ca5d7b7df.png)

I want to go here, which I'm going to say we call the "Submitted Datapackages" page:
![image](https://user-images.githubusercontent.com/1719360/109313883-b1a61f80-7816-11eb-90bf-3a6966fb72bc.png)

This is different from the old behavior. In the old behavior, clicking "Data Review" took you to the single "Data Summary" page that existed:
![image](https://user-images.githubusercontent.com/1719360/109314886-e797d380-7817-11eb-8bef-a1858644f330.png)

But, we need this new behavior, because any given DCC can now have more than one submission at a time. So, we need the "Data Review" button to send them to the list of data packages they have submitted, so they can choose which summary to view. Otherwise we would have to choose one of their packages to be the default in "Data Summary" and constantly update which one was the default as they submitted new packages and rejected old ones.
 
In staging, I have only seen it do the new, correct behavior, but if there are places where it is not doing the new behavior, we should fix that right away, or people with multiple submissions will be very confused. 

Now that I've written this out, I wonder if we should change the title of that first button that currently says "Data Review" to something more descriptive of what the process has become? Maybe something like "Submission System"? or "Data Review System"?

**Comment by karlcz** [comment]
Yes, the new behavior is as-intended to deal with multiple submissions being available to review, and each one having its own charts page.  The "dcc_review.html" page name is a misnomer as it is really a "submission_review" function.

I think Josh is just observing that it is different than what we used to have where the navbar went straight to a charts page (with no UX provision for multiple submissions/multiple DCCs being visible to one user).

**Comment by jrchudy** [comment]
Ah thank you, I didn't realize the requirements for the navbar had changed regarding this link on static pages.
