### ISSUE TITLE
Provision profiles storage in dev registry

### ISSUE THREAD

**Issue by jrchudy** [nih-cfde/cfde-deriva#170]
Once the profiles storage relational model is defined:
- [x] Add tables to dev registry
- [x] Load initial controlled vocabulary terms to registry's new CV tables

**Comment by karlcz** [comment]
The profile-related tables are now provisioned in the app-dev registry. Namely,
- `user_profile` which has a rudimentary Chaise UX at this time
- `saved_query`
- `favorite_dcc` associates to existing registry `dcc` table
- `favorite_anatomy` associates to new `anatomy` CV table copied from C2M2
- `favorite_assay_type` associates to new `assay_type` CV table copied from C2M2
- `favorite_data_type` associates to new `data_type` CV table copied from C2M2
- `favorite_file_format` associates to new `file_format` CV table copied from C2M2
- `favorite_ncbi_taxonomy` associates to new `ncbi_taxonomy` CV table copied from C2M2
- `favorite_subject_granularity` associates to new `subject_granularity` CV table coped from C2M2
- `favorite_subject_role` associates to new `subject_role` CV table copied from C2M2
Most of these are empty while work continues on related issues.

**Comment by karlcz** [comment]
The vocab terms from the 7 submissions in the last CFDE release should now be present in the app-dev registry

**Comment by karlcz** [comment]
The `saved_query` table definition was changed slightly after this issue was already moved to QA:
- added a client-supplied `id` column
- removed compound key over `user_id`, `table_name`, `facets` to avoid problems later
- annotations changed to prevent a user from adding saved query records via recordedit
So, the model doesn't care if you store "duplicate" queries. It is up to the client to decide what level of duplicate detection should be a part of the UX. If it wants to do so, it should include some hashed value in the `id` (perhaps a mixture like user id + '/' + hash?) and then perform appropriate ermrest lookups to test for an existing record with that hash.

**Comment by karlcz** [comment]
The `user_profile` table has been extended with a `dashboard_state` JSON field.

The `saved_query` table has been revised:
- `id` column dropped
- `schema_name` field added (w/ default value `CFDE`)
- `query_id` field added as query hash
- primary key changed to composite (`user_id`, `schema_name`, `table_name`, `query_id`)
This composite key returns to a state where the client-generated hash is per-user and we do not have to worry about potential collisions between different users' activities, regardless of how they use or abuse infrastructure.
