### ISSUE TITLE
submission validates, does not display

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#173]
I am helping a new DCC make a brand new data submission, and am pre-validating it for them. I locally ran a frictionless validator and it passed, so I just submitted it to the testing DCC on production. and the summary chart does this: https://app.nih-cfde.org/dcc_review.html?catalogId=14

Clearly, there is something wrong with their files that the validator didn’t catch, and I need to go through the files manually to figure out what that is. But I feel like this should not have imported perfectly fine and show content ready for review if there’s something so wrong with it that it can’t make a dashboard page.

![image](https://user-images.githubusercontent.com/1719360/110992063-6bd37600-8343-11eb-872d-5e5539394915.png)

**Comment by ACharbonneau** [comment]
This is a new DCC that doesn't have data in the portal yet, so @jonathancrabtree is going to check to see if the plot code is just not getting new DCCs for some reason

@ACharbonneau is going to add an abbreviation to the project table and resubmit to see if that helps. If it does, need to check model requirements

**Comment by ACharbonneau** [comment]
Good news! Adding an abbreviation does make it load properly. However the UI is not handling the description well:
![image](https://user-images.githubusercontent.com/1719360/110993054-cfaa6e80-8344-11eb-871b-7cb63e41d313.png)
https://app.nih-cfde.org/dcc_review.html?catalogId=17

**Comment by ACharbonneau** [comment]
from @abradyIGS 

```
`primary_dcc_contact.project_id_namespace` and `primary_dcc_contact.project_local_id` together constitute a foreign key into the project table. This key is meant (required) to point to the top node in the project hierarchy, which by convention represents the DCC itself.

`primary_dcc_contact.dcc_abbreviation` should replicate `project.abbreviation` for this top-level node.
we can just make the former (the abbreviation field in `primary_dcc_contact`) required and leave the `project` table per se alone.
i'm sure this is going to cause display stupidities as people expect things to be labeled by actual project designations, but i assume we can further hash out best practices with DCCs once a few more pathologies have rolled in.
```

So, I think that means arthur is going to update the model spec to require an abbreviation in `primary_dcc_contact.tsv` and Jonathan is going to make his queries use that instead of the project abbreviation.

Additionally, we're going to delete the top right box thing that looks like this ONLY FOR REVIEW PAGES. It says on the homepage and anywhere else it exists:

![image](https://user-images.githubusercontent.com/1719360/110998156-66c6f480-834c-11eb-8824-857462e19cce.png)

If this last point causes problems, or is bad for some reason, let me know.

**Comment by karlcz** [comment]
If there are going to be model changes we may need more issues or subtasks to track the detailed integration bits...
- Change to Arthur's model docs/references
- Change to portal model built into cfde-deriva
- Change to dashboard-queries module in cfde-deriva (if needed)
- Change to dashboard api web service (if needed)
- Change to dasboard and review page apps

**Comment by karlcz** [comment]
I'm going to bulk add some assignees here with the idea that we either add checklist to this issue or people make sure appropriate issues for tasks exist elsewhere and then remove themselves from this one if redundent...

**Comment by karlcz** [comment]
@ACharbonneau is this issue supposed to be linked to the March delivery?

**Comment by ACharbonneau** [comment]
I really would like this fixed for the end of March if we can. I've already had multiple DCCs have this problem :( 

Follow up question: I told someone yesterday that their datapackage was fine, and that it was just the review summary plots that were buggy, so they didn't have to resubmit. But then I woke up in the middle of the night wondering if *all* our plots are using this hack? Because if this is going to keep data from showing on the homepage, then it for sure needs to be fixed for March AND I need to make some people go redo their submissions to add abbreviations in the contact table, so I need to know asap

**Comment by abradyIGS** [comment]
I can change the published schema whenever, but I don't want to accidentally create a clash with the portal model built into Deriva.

@karlcz given the checklist you drafted above:

- [ ] Change to Arthur's model docs/references
- [ ] Change to portal model built into cfde-deriva
- [ ] Deployment of updated model requirements in action provider
- [ ] Change to dashboard-queries module in cfde-deriva (if needed)
- [ ] Change to dashboard api web service (if needed)
- [ ] Deployment of updated dashboard api service w/ embedded dashboard-queries module
- [ ] Change to dasboard and review page apps

The first one is no problem: I just add a non-null constraint to `primary_dcc_contact.dcc_abbreviation`, which I'll do as soon as we have a deployment plan (so that I don't accidentally break something I don't understand on the load side).

@ACharbonneau unless i got something wrong, this deployment plan will involve reloading all the already-submitted data after the necessary schema changes have been made, so it probably has a few more steps than the ones given above?

**Comment by ACharbonneau** [comment]
> @ACharbonneau unless i got something wrong, this deployment plan will involve reloading all the already-submitted data after the necessary schema changes have been made, so it probably has a few more steps than the ones given above?

Am I supposed to be reading this as "we rebuild the already submitted data" or "Amanda has to ask all the DCCs to resubmit their data"?

**Comment by abradyIGS** [comment]
I was referring to `I need to make some people go redo their submissions to add abbreviations in the contact table`. What I meant was just to note that whatever DCCs that's true for will need to replace their submissions, if any have been loaded.

**Comment by abradyIGS** [comment]
sorry, i did say "all" -- i think i meant rebuilding the production catalog, but please ignore any stray words that don't look like they should be there.

**Comment by abradyIGS** [comment]
to rephrase my thing: i will change the schema whenever someone tells me doing so won't break things

**Comment by abradyIGS** [comment]
Have pushed a non-null constraint to:
* the three ER diagrams in the tech documentation
* the published JSON schema (both copies: one on (github)[https://github.com/nih-cfde/c2m2/tree/master/draft-C2M2_JSON_Schema_datapackage_specs] and the other on (OSF)[https://osf.io/e5tc2/])

@karlcz suggests trying a test submission with the new tighter constraint, shouldn't cause a fuss

meanwhile he'll update the deriva-side schema and initiate a push to dev for testing

after that, jonathan can test the proposed change to the table from which display abbreviations are pulled.

**Comment by karlcz** [comment]
RIght, we can do all these tests on dev.
1. Test the newly revised submission w/ existing dev (to see that it accepts a "more strict" submission model)
2. Test newly revised submission w/ updated dev (to see that the change continues to work as expected)
3. Re-test an old submission w/ updated dev (to see that it is rejected by the ingest service which knows a "more strict" model after the update).

**Comment by ACharbonneau** [comment]
Sorry. I promise I will run a test tomorrow. But I am out of brain for today :(

**Comment by ACharbonneau** [comment]
OK. I ran a package with the new schema, it submitted fine. I deleted the abbreviation and tried again, and the tool rejected it with a useful error message:

```
(cfde_venv) (base) amandas-mbp-2:helperscript amanda$ cfde-submit run ~/Downloads/noabbrev/ --output-dir=../../Downloads/hubmapsubmitnoab --dcc-id cfde_registry_dcc:test1
Submit datapackage '' using cfde_registry_dcc:test1? (y/n)? > y
TableSchema invalid due to the following errors:
Field "dcc_abbreviation" has constraint "required" which is not satisfied for value "None"
```

So this seems good

**Comment by jonathancrabtree** [comment]
@ACharbonneau to answer your follow-up question from a few days ago, yes, this issue absolutely affects all the plots, not just the DCC review page. Now that we've made it customizable, that graph/plot is no different from the one on the home page or those on the dashboard page. As I think I said when this first came up, the problem is that I wrote dashboard-api to use the DCC project.abbreviation as the "DCC moniker" or unique DCC identifier. In Epic 1 and Epic 2 there simply was no other field in our release catalog (except perhaps for the DERIVA internal RID) that looked like it could possibly have been used for the purpose intended by the API spec. Yes, in hindsight I should have checked that it was non-nullable in the schema, but I was operating under the assumption that the developers of the database weren't actively trying to trick me :) In fact I probably would still have used that same field even if I'd known it was nullable (because that table stores all projects, not just the ones that correspond to DCCs and it would be rather onerous to make it non-nullable for all of them), although I might have mentioned it as a possible concern, or implemented a fallback to RID to cover the case where it was null.

The good news is that fixing things on the dashboard side of things shouldn't require any changes in the dashboard repo, just in dashboard-api, and that work is covered by https://github.com/nih-cfde/dashboard-api/issues/26 (and shouldn't take long.)

**Comment by jonathancrabtree** [comment]
I'm working on updating dashboard-api to pull the abbreviation from primary_dcc_contact and currently in app-dev catalog 1 it looks like 4DN is the only one of the 7 DCCs with a null value in primary_dcc_contact.dcc_abbreviation. Reading over the comment history in this issue I think that's to be expected because the non-nullable constraint has not yet been pushed to DERIVA app-dev.

**Comment by jonathancrabtree** [comment]
dashboard-api has been updated (on GitHub master). Once we have a live catalog with the new non-nullable dcc_abbreviation constraint it can be tested in dev. No changes should be needed in dashboard (unless we want error handling for the specific case of someone pointing the new dashboard-api at a catalog without the non-nullable constraint on dcc_abbreviation.) As per Arthur's request, there's no graceful fallback so the updated dashboard-api is by design not compatible with previous schema versions.

**Comment by karlcz** [comment]
Content now exists on app-dev to test this for submissions and release data.

**Comment by jonathancrabtree** [comment]
Looks like maybe app-dev doesn't have the latest dashboard-api (from ~6 days ago) yet. One of the DCCs is showing up as "AllProjects" whereas I think it should be "MW" in primary_dcc_contact.dcc_abbreviation.
