### ISSUE TITLE
Change or highlight ingest status?

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#177]
A DCC was unsure whether a datapackage was okay, because the didn't see any diagnostic info. Example of failed vs. good package view:
![image](https://user-images.githubusercontent.com/1719360/111523072-3f4b9f80-8731-11eb-92e6-9558d68592b4.png)

Basically, since it didn't have diagnostics, they thought that meant it didn't work. 

I'm thinking we should change the 'good' Ingest Status to something like "Success" rather than 'content ready for review', or maybe "Success! Content ready for review". Just something that more clearly denotes it as a positive. And maybe bold it?

**Comment by karlcz** [comment]
On some other projects, I think we've seen success applying CSS styling classes to similar workflow status coded values so they could include a color change or a little icon in the HTML presentation. I wonder if that's more what we need here.  The current displayed text is the display "name" for a status term in the controlled vocabulary of submission state values.

**Comment by jrchudy** [comment]
This is how we style it in another project:
![image](https://user-images.githubusercontent.com/2932600/111817867-c6b52200-889b-11eb-9e86-daa97a5de585.png)

**Comment by karlcz** [comment]
The partially completed changes for the registry wireframe have a field "Ingest Status" in the per-submission card views. This is one field that should get this kind of colored disc decoration.

The states come from the https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:datapackage_status vocabulary. Here is a summary of status values and potential coloration:

Submission is in-progress but its validity not yet fully determined (maybe a light/faint green?):
- submitted
- bag-valid
- check-valid

Submission has been fully processed and is valid (green?):
- content-ready
- release-pending (note, this state currently not implemented)

Submission found to have problems (red?):
- bag-error
- check-error
- content-error

Submission rejected by human reviewer (light/faint red?):
- rejected (note, this state currently not implemented)

Submission ingest stopped with other error (yellow?):
- ops-error

Submission retired/superceded (gray or also green?):
- obsoleted

**Comment by karlcz** [comment]
Similarly, the card view has a "DCC Approval Status" field with states from https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:approval_status  and it has these relevant states and potential coloration:

- pending (gray?)
- approved (green)
- rejected (red)

**Comment by karlcz** [comment]
The submission card view now also has a "Release Status" field which is generated by a bit of a hack. It gathers the distinct status values from all releases connected to the submission, sorts them by a new `dp_rank` field on the status vocab table, and displays the highest priority term according to this sort. The terms are from https://app-dev.nih-cfde.org/chaise/recordset/#registry/CFDE:release_status  summarized with suggested coloration:

The submission is part of the current public release (light/faint green?), where `dp_rank` == 1.0:
- public-release

A new/future release is pending with this submission as a constituent (green?), where `dp_rank` == 2.0
- planning
- pending
- content-ready

The submission was part of a prior public release (light green or gray?), where `dp_rank` == 3.0:
- obsoleted

The submission is part of a failed release (yellow or no color at all?), where `dp_rank` is null:
- content-error
- ops-error
- rejected

Generally speaking, this last category does not necessarily mean that a submission is bad in any way. The release might be rejected or failed due to problems with infrastructure or with _other_ submissions in the release, and not reflect any actionable information about any particular submission. This might be an argument for hiding this state or at least coloring it in a neutral fashion?

We also might want to code a special case in the display template, to recognize the status array that starts with ranks [1.0, 2.0, ...] and color it in some special way to indicate that it is _both_ part of the current public release and planned as part of the next release. If we do not care about this state, we could also just modify the `dp_rank` assignments to priorize the future release status over the current release status. However, that would then mean that the public release value can appear at multiple offsets in the array, and detection of this special corner-case would be more difficult with the limitations of the display template syntax.

**Comment by karlcz** [comment]
I've added class names that map states into a slightly more abstract set of classes we can then decorate with a color/symbol:
- `cfde_noinfo`  : a light gray filled circle
- `cfde_pending` : a green hollow circle
- `cfde_success` : a green filled circle w/ a checkmark
- `cfde_retired` : a green hollow circle with a checkmark
- `cfde_rejected` : a red filled circle with an X
- `cfde_error` : a yellow (or orange?) solid circle with exclamation mark
