### ISSUE TITLE
Initial SQL-based c2m2 validators

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#189]
- [x] Add generic machinery to allow SQL queries in the portal model to be used for validation (in sqlite intermediate db)
- [x] Enforce file checksum requirement
- ~Checks for completeness of the cross-entity association tables~

**Comment by karlcz** [comment]
I need to reconvene with modeling group to clarify what the completeness checks should enforce as mandatory structure.  Also, do we need some weaker form of checks that produce warnings (with unknown but necessary new UX) without blocking the ingest? Maybe that's better done as client-side tools though...

**Comment by ACharbonneau** [comment]
@abradyIGS does your plan for client side cover this?

**Comment by abradyIGS** [comment]
Yes, if you remove the "SQL" part. The current iteration of the client-side submission-prep script performs the following validations:

* ensure all persistent IDs are unique (including across different tables)
* ensure that for each file record with a non-null persistent ID, at least one non-null checksum is provided

I can expand the validator module to do pretty much anything, now; @karlcz if you want to send me precise descriptions of the proposed completeness checks in this thread, I can just fold them into the code and report back (unless there's something we disagree about, in which case I'll add it to an upcoming agenda)

**Comment by karlcz** [comment]
It sounds to me like you're talking about a parallel but independent
tool and features.

This issue is about validators embedded in cfde-deriva and executed
in the ingest process.  A client-side tool is not a substitute, since
its use is not enforcable by the service.

But, if we don't see a need for additional enforced checks right now
in the service, we could close this and open enhancements later.  An
initial check is already implemented to require a checksum.

**Comment by abradyIGS** [comment]
> It sounds to me like you're talking about a parallel but independent tool and features.

I realize belatedly that I am, yes, and it is logged [here](https://github.com/nih-cfde/c2m2/issues/49).

> A client-side tool is not a substitute, since its use is not enforcable by the service.

That's mostly down to a technicality, because it would be extremely difficult for DCCs to physically prepare a valid submission _without_ using this tool, not to mention the fact that doing so is expressly prohibited at this point.

Like you suggest, though, we're going to end up needing either

* a fully-secured automated ingest service independent of the client-side tool, which would (as you say) require explicit verification that structural compliance (as enforced by the client tool) is still intact on receipt of incomingdatapackage, or
* to fold this client-side tool directly into the submission software

Either way, I support your last suggestion that we table this issue until/unless it becomes a higher priority because I don't see a need for additional checks right now in the ingest service.

Please go ahead and close if there is no disagreement, and send me descriptions of any checks (not currently performed anywhere) you think would be a good idea to add.

**Comment by abradyIGS** [comment]
PS. please submit any feature requests as comments [here](https://github.com/nih-cfde/c2m2/issues/49)
