### ISSUE TITLE
develop CFDE UI documentation

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#22]
Start: 6/1/20
End: 7/1/20

Milestone: 5

POC: @mikedarcy 

https://github.com/nih-cfde/deliverables/issues/104

**Comment by RLC-DCPPC** [comment]
link to relevant deliverble

**Comment by RLC-DCPPC** [comment]
Consider combining with #25

**Comment by RLC-DCPPC** [comment]
Hi @fridayek .  We have [this ](http://docs.derivacloud.org/users-guide/using-chaise.html) from @mikedarcy as a possible starting place.

My thought is that we need a general User Guide for the CFDE UI (i.e. dashboard and portal) but they could be combined. Let's discuss after we've had a change to review the above doc.

**Comment by fridayek** [comment]
@RLC-DCPPC Thanks for the starting place. I use a documentation tool called MadCap Flare that allows me to enter information in one place and create multiple output types. For example, I can create PDF user guides for each site (dashboard and portal) or by user type, or I can export it in HTML so the text displays like a separate website. I can show you some examples, if you want to meet at some point to discuss.

**Comment by RLC-DCPPC** [comment]
Hi @mikedarcy . We have this [deliverable ](https://github.com/nih-cfde/deliverables/issues/104)on the calendar for the end of the month.

I've been discussing with @fridayek , and our thought is to go ahead with a small document on using the portal for delivery then. But, we like the idea of including some on-line and/or context-sensitive help in the next version of the tool (perhaps to replace this document). So, can you and Erin spend a little time in the next week to chat about this and provide Erin some information for her to put in said document? We might need a short follow-up meeting after the demo, to review/update for any last-minute changes, as well.

Please let me know if you think this schedule is not feasible and we can think about getting an extension for this activity.

**Comment by mikedarcy** [comment]
Seems reasonable. However, if you are shooting for CFDE-specific, function/context-sensitive help in the DERIVA Portal interface by the end of month, that might be pushing it. If we just want this material in a document that is hosted on-line and linked to by the portal interface in a top-level menu, that is do-able.

**Comment by RLC-DCPPC** [comment]
Renamed since we are now delivering combined documentation.

**Comment by RLC-DCPPC** [comment]
Met with Erin, Mike, and Victor to discuss and plan.

[Deriva link](http://docs-new.derivacloud.org.s3-website-us-west-2.amazonaws.com/user-guide/introduction.html): 

[Chaise link:](http://docs.derivacloud.org/users-guide/using-chaise.html)

**Comment by fridayek** [comment]
I created the following draft based on the information provided in this ticket and from the team:
https://docs.google.com/document/d/1S5ll51sKuFuV3uzCQrCZM_y23nqevP55x42guhAsuOI/edit#

**Comment by ACharbonneau** [comment]
@s-canchi Can you put your comments for Erin on the UI help document here please?

**Comment by s-canchi** [comment]
## CFDE Portal & Dashboard Help Documentation - SCanchi Review

The Common Fund Data Ecosystem (CFDE) [portal and dashboard documenation](https://docs.google.com/document/d/1S5ll51sKuFuV3uzCQrCZM_y23nqevP55x42guhAsuOI/edit#) was the basis of the review.

## Section: Introduction

The first page has some repetitive concepts along with terms that would have wider acknowledgement within CF programs than outside audience. 

Login details are standard but the current purpose is unclear as the portal functionality is available without logging into the portal.

## Section: Portal

### Filter the Chart

This section lists the various options available to view the different types of CF data. What is currently missing but would be useful is addition of summary points for the different charts as the take home message is not always clear.

### Explore the Repository

This section describes the different features of the repository ("data browser") along with the different filtering options. 

- The steps listed repository access are written as bullet points and can be confusing as they imply sequential steps for the user.
- The section has multipe subsections divided by the the different features available to browse the repository.
- Each subsection has information on accessing the key feature, details on the resulting data table and the list of available filters.
                  -   The filter list for the Refine Search panel contain terms that are not explained and they change depending on the feature choice i.e. The number of filters available to Refine Search when feature is Collections is not the same when the feature is Biosample. This aspect should be explicitly mentioned in the documentation. 
- Some connecting steps have to be written to be explicit. For example in the *View Details* subsection, you can scroll down the page to obtain the same sections listed in the left hand panel.
- In the *Export Search Results* the available options for csv or BAG are only applicable in the *View Details* page. For *Export* from the main browser page only csv option is avialable. 

## Section: Dashboard

The first bullet point in the top level summary about the two bar charts has two corrections:
  > The X-axis, Y-axis, and Stack are configurable to all users to customize the data summaries as needed.
   - Should be "..configurable by all users.."
 > These bar charts display next to each other so you can compare two different data summaries.
  - Should be "These bar charts display one on top of another..."

This could be an UI issue, but the colors in the example screenshots do not match the actual colors in the Dashboard.

### Filter the Bar Charts

> The ... axis of the bar chart updates automatically with the option selected
- This sentence repeats itself for each of the bullet point and could be a top level summary instead. 

> The title of the chart updates as well to reflect the option selected.
 - This sentence is repeated three times and could be added as a top level summary instead.

### Filter the Anatomy by Common Fund Program Chart

In the first point about selecting the CF program only the GTEx acronym is expanded. It would be better to expand all where applicable. 

I couldn't test out the export options listed in Export the Chart as it did not work. 

**Suggestions:**

- Add a glossary or list of all available filters and features along with their definitions at the start instead of defining them as they appear
- Would be useful to provide individual program links 
- Would be useful to provide some context to the users while defining the different browse options
- If there is a functionality for intra document linking, then it should be used to link relevant subsections when introducting concepts at the start
- Provide spacing between paragraphs when jumping topics
- Would be useful to list some example searches or use cases for the repository
- Would be useful to provide example of comparative data summary for Dashboard Bar charts

**Comment by s-canchi** [comment]
Additional clarification from Erin about the CFDE Portal documentation:
Could you add some notes to explain the different columns in the exported csv file ? Specifically - RID, RCT, RMT, RCB, RMB, PROJECT_ID_NAMESPACE
These values are not explained in the current documentation for portal or C2M2.

**Comment by RLC-DCPPC** [comment]
Hi @s-canchi , @fridayek , can we jump on a Zoom call and knock this out this week? How about tomorrow (10/14) at 3:30 EST?

**Comment by fridayek** [comment]
@RLC-DCPPC That works for me, Bob. My afternoon is open tomorrow.

**Comment by mikedarcy** [comment]
These columns are basically internal metadata which are hidden from the user in the web portal view but are included in exports for proper record provenance.

The following columns are internal "default" metadata included in every Deriva table:

- RID: This is the internal "Record ID", which could be thought of as a "primary key".
- RCT: This is a timestamp representing the "Record Creation Time".
- RMT: This is a timestamp representing the "Record Modified Time".
- RCB: This is "Record Created By" which is a GlobusAuth identity string (GUID) representing the creator of the record.
- RMB: This is "Record Modified By" which is a GlobusAuth identify string (GUID) representing the user who last modified the record.

The PROJECT_ID_NAMESPACE is a C2M2 column that represents the unique DCC namespace identifier assigned by the CFDE to the DCC.

**Comment by s-canchi** [comment]
Tomorrow at 3:30 pm (EST) works for me too. Let me know if you need my email id.

**Comment by s-canchi** [comment]
Highlights of the meeting with @fridayek @RLC-DCPPC on 14th Oct, 2020: Possibility of changing UI for portal. End date is currently not fixed. The UI documentation could be added to the portal under documentation or linked from the training website. Training team can help with converting to markdown format and hosting on our site and @s-canchi will link the training website after the October release here.

**Comment by RLC-DCPPC** [comment]
Spoke with @ACharbonneau later in the day and we decided that we do need the manual updated for the end of October release even if the screenshots are not quite up-to-date (@fridayek is working on this now). There is a "FAQ" button/link in the UI (?) that should point to the updated manual. I will check with @victor73 and @jrchudy as to what format the manual needs to be in. Perhaps the manual/user guide can live in the readthedocs area and also be in some "list of available docs" over there?

**Comment by ACharbonneau** [comment]
If need be, we can put it in readthedocs, but I'd prefer if we can get it natively in the UI rather than directing people out to another site.

**Comment by RLC-DCPPC** [comment]
HI @fridayek, how are the revisions coming along?

**Comment by fridayek** [comment]
@s-canchi @RLC-DCPPC - I updated the User Guide with @s-canchi's comments above and with the latest functionality. Should I expect any more functionality changes before the end of the month? 

Here are some comments that I had remaining questions on:
- _Hovering the arrow and clicking on the portal shows CFDE Dashboard as the title underneath_ - This change will need to be done by a developer since the browser tab says the same thing.
- _Login details are standard but the current purpose is unclear as the portal functionality is available without logging into the portal_ - I kept this because login functionality may occur in the future. Should I remove it from the User Guide for now?
- _Would be useful to list some example searches or use cases for the repository_ - Do you have examples I can use? I don’t know enough about the data to create a meaningful real-world example.
- _Would be useful to provide example of comparative data summary for Dashboard Bar charts_ - See my comment above.

**Comment by ACharbonneau** [comment]
> @s-canchi @RLC-DCPPC - I updated the User Guide with @s-canchi's comments above and with the latest functionality. Should I expect any more functionality changes before the end of the month?
> 
> Here are some comments that I had remaining questions on:
> 
> * _Hovering the arrow and clicking on the portal shows CFDE Dashboard as the title underneath_ - This change will need to be done by a developer since the browser tab says the same thing.

Can @jrchudy or @victor73 confirm this is a thing we're fixing with the wireframes?

> * _Login details are standard but the current purpose is unclear as the portal functionality is available without logging into the portal_ - I kept this because login functionality may occur in the future. Should I remove it from the User Guide for now?

Log in will do something for some users by the end of october. I would leave it.

> * _Would be useful to list some example searches or use cases for the repository_ - Do you have examples I can use? I don’t know enough about the data to create a meaningful real-world example.

I think this doesn't go in this doc, as we're aiming for more of a reference guide. I think use cases/examples belong in the training/tutorials for now, we can come back to it for a later iteration if we decide it's needed

> * _Would be useful to provide example of comparative data summary for Dashboard Bar charts_ - See my comment above.

I think this doesn't go in this doc, as we're aiming for more of a reference guide. I think use cases/examples belong in the training/tutorials for now, we can come back to it for a later iteration if we decide it's needed

**Comment by RLC-DCPPC** [comment]
Hi @victor73, @jrchudy : Can you work with @fridayek to get the manual wired into the UI according to the wireframes? Happy to facilitate a meeting if that helps.

The current plan is to have Erin make final updates to the manual after the code/data freeze on Monday so she can base it on the actual implementation ;-) and then get it wired in  before the delivery on Friday.

**Comment by ACharbonneau** [comment]
Temporary solution: https://github.com/nih-cfde/published-documentation/issues/101

We'll still need to get it into the UI proper, but for Tuesday we're linking out to a temp version in the documentation site. @fridayek should work with @jeremywalter on it. He's working to translate her doc into markdown now.
