### ISSUE TITLE
How does a user get to their favorites management interface?

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#223]
I thought I remembered Josh having a Favorites button on the top right of each page that let you get to the pages like: https://app-staging.nih-cfde.org/chaise/recordset/#registry/CFDE:favorite_anatomy@sort(RID)

**Comment by jrchudy** [comment]
The page Karl linked is the one I showed when demoing the feature initially. I should have made it more clear how I got to that page and that it was something we are intentionally NOT exposing to the user because we want the dashboard interface to be used instead.

The "My Profile" link under the username dropdown shows information that the user_profile record page doesn't include so we might want to think about a different way to access this deriva page if we want users to be able to get there.

**Comment by ACharbonneau** [comment]
That's fine if we're not showing it. I just wasn't sure.
