### ISSUE TITLE
Unfriendly error when a favorited term no longer exists

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#259]
Not sure if this belongs to deriva or dashboard or both

At some point I had favorited "enzyme-linked immunosorbent assay" which is no longer in the catalog. It is still in my favorites list:
![image](https://user-images.githubusercontent.com/1719360/139296551-fb16b014-9643-4f47-825f-990a0b8e36d7.png)

but trying to view it gets me:
![image](https://user-images.githubusercontent.com/1719360/139296298-727c3b60-6ab8-4914-9834-55ed7e3a027b.png)

and hitting "ok" dumps me to the assay table for some reason:
![image](https://user-images.githubusercontent.com/1719360/139296712-39967144-de63-4c77-a38d-31a443b11199.png)

**Comment by jrchudy** [comment]
This will be focused on during next quarter as "Epic 2 technical debt".

**Comment by mschor** [comment]
Hi, I noticed this is assigned to me. I would ask that we discuss a clean solution. As I understand it, one proposed solution is to get back a user's favorites from Deriva and then for each favorite, check back with Deriva if this favorite is valid or not be determining if the term still exists. Unless I'm missing something here, this seems like a clunky workaround to me. Why aren't we just deleting a favorited term when the term itself is deleted?

**Comment by jrchudy** [comment]
There are 2 cases that Karl brought up in his comment above that could be causing this:
> 1. a DCC user marked favorites from in-review data that is not released
> 2. a DCC actually stops using a term in future releases that they used in the past, and users have favorited it in the older release data

We had 3 suggestions come up in the UX meeting today: 
 - Because of his, we need the personal dashboard to be smarter about the links it generates. Karl suggested we could check if a link exists (verify a favorite exists in catalog 1) before creating a link or showing it at all. This may be cumbersome to do for _every favorite_ since the user could have a very large amount.

 - A solution in the opposite direction would be to NOT link the favorites to their respective record pages. The favorites are vocabulary terms and don't have much meaningful information for that record. Although it does show related contents (like files and collections) that might include that favorite.

- Another suggestion is to provide a link to specific set of favorites on the user_profile page for each widget.
   ![image](https://user-images.githubusercontent.com/2932600/141531643-643b331f-63ef-49bc-a9da-cb7ac3a3246a.png)
   
   links to here:
   ![image](https://user-images.githubusercontent.com/2932600/141531721-c30e9d1e-926c-419b-915c-9b6f617e05a8.png)

**Comment by jrchudy** [comment]
@ACharbonneau stated today in the UX phone call that user's favoriting terms in review catalogs that don't make it to the release catalog is not important. 

She also mentioned that terms will be removed as part of data curation and this may occur as soon as the end of January.

**Comment by ACharbonneau** [comment]
I was wondering if when we build a new catalog for the quarter if we could just purge any favorites that aren't in the new catalog 1. I 100% don't care if that breaks favorites that are in some random review catalog. Favorites are a feature for end users, for use with catalog 1.
