### ISSUE TITLE
2021Q3 personal collections

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#268]
To support shopping cart/export flow.

- [x] `personal_collection` table
- [x] `personal_collection_file`  associations (per collection/list)
- [x] export BDBAG from `personal_collection` page
-  ~`shoppingcart_file` association (link file to profile/shopping cart)~
- [~export BDBAG from profile/shopping cart~
- [x] policies to allow low-privilege "community member" (profile-holders) to see and manipulate their own selections

Other export format(s) should be introduced as new issues, and defined holistically to work on basic search results and/or personal collection and/or shopping cart, as appropriate.

**Comment by karlcz** [comment]
This has been prototyped in a couple hand-built catalogs on app-dev. The shopping-file association was trialed but provides a more confusing UX than the personal collections concept, so should probably be shelved for now.

We're going to investigate a few Chaise enhancements which might incrementally improve the personal collection UX.  But, we think the current behavior is an adequate MVP to allow user-driven selection of files for export.

**Comment by karlcz** [comment]
This needs just a little bit more review before we might say it is ready to merge and start using in app-dev as part of the base for other CI work this quarter...

**Comment by karlcz** [comment]
This was merged to master so some of its changes can be included with forthcoming c2m2 changes during this dev cycle.  If we decide to change the personal collection details, we'll do it in-place rather than reverting this branch's changes.

**Comment by ACharbonneau** [comment]
OK. I have poked this and it seems like the basic functionality is working. I have a few comments for things we should improve either now or in coming quarters, depending on difficulty:

- For files without persistent ids, it doesn't let me add them, but doesn't give any indication why. I think hover text on the greyed out button would be good
- we need quite a lot of documentation to make this make sense to someone, I think @fridayek might want to start figuring this out from dev rather than waiting
- There should be a widget in the dashboard of my personal collections that functions much like the saved searches, it is super not obvious how to get to personal collections otherwise
- It would be good if the filter panel was open by default when I click "add record" when on my personal collection page to do a bulk add. it's very not obvious that you can filter from there
