### ISSUE TITLE
Search timeout with Programs

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#308]
I was just trying to show an actual researcher how to use the portal to find the data they want, but it died :(

I had filtered datatype and datatype slim as:
![image](https://user-images.githubusercontent.com/1719360/152561016-690ef036-0dee-4741-a196-aa965918881b.png)
 then clicked "Show more" on the Common Fund Program filter because their question was which DCCs have those datatypes:

![image](https://user-images.githubusercontent.com/1719360/152560574-129b9d5b-3524-49fa-ab08-1fbd57d4a8f5.png)

**Comment by karlcz** [comment]
I somewhat reproduced this using just the "slim" options above and then moving on to look at Common Fund Program. It did not show a timeout but the "browse more" modal takes over 40 seconds to get results.

These are notes from investigating, but not yet any resolution:
- the facet control itself opens easily and produces a list of DCCs
- opening the modal creates a long-running query to find the first page of results

Naively, we'd hope the modal shouldn't be doing anything too much more complex than the facet itself, but Chaise actually poses totally different queries for the two scenarios and the former happens to be much faster in this case...

The query Chaise does for the fast listing in the facet control:
```
.../entity/T:=CFDE:file/(core_fact)=(CFDE:core_fact:nid)/(nid)=(CFDE:core_fact_data_type:core_fact)/(data_type)=(CFDE:data_type:nid)/is_slim=true/nid=7;nid=35;nid=48;nid=49;nid=3/$T/(core_fact)=(CFDE:core_fact:nid)/(nid)=(CFDE:core_fact_dcc:core_fact)/M:=(dcc)=(CFDE:dcc:nid)@sort(nid)?limit=11
```

The query Chaise does for the slow/hanging modal page:
```
.../attributegroup/T:=CFDE:file/(core_fact)=(CFDE:core_fact:nid)/(nid)=(CFDE:core_fact_data_type:core_fact)/(data_type)=(CFDE:data_type:nid)/is_slim=true/nid=7;nid=35;nid=48;nid=49;nid=3/$T/(core_fact)=(CFDE:core_fact:nid)/(nid)=(CFDE:core_fact_dcc:core_fact)/M:=(dcc)=(CFDE:dcc:nid)/F1:=left(project)=(CFDE:project:nid)/$M/nid;M:=array_d(M:*),F1:=array_d(F1:*)@sort(nid)?limit=26
```

I experimented with removing the extra joins to find "project" info (which we don't actually need for this UI display) and reduced the query time by about 50% (from ~40s to ~20s) but it is still drastically different than what the first query does in under 1s. I think I can reconfigure things so that this improvement happens in this scenario.

Switching it back to the /entity/ API makes a huge difference here.  Unfortunately, I don't think that's currently a behavior I can coax out of Chaise via any sort of portal catalog configuration change.  I'm also not sure it is a generalizable win or a peculiar aspect of this query and the postgres query planner, which might penalize other scenarios if we tried to get Chaise to switch to the /entity/ API on its own.

**Comment by karlcz** [comment]
Another observation is that this is actually a really tortured use of the DB as it is asking for queries around "file" even though we don't care about files per se.  If we exposed more core\_fact-derived facets directly on the "dcc" table, we might be able to provide much faster UX for finding which programs are connected to which vocabulary terms...

Would that be of interest, or is the UX too obscure such that this work would go unnoticed/ignored?  You'd have to use the navbar to go Data Browser -> Common Fund Program and then make use of similar facets there which would mimic choices we have now on File/Biosample/Subject.
