### ISSUE TITLE
CLI Tool updated for use by researchers

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#318]
Mike is going to make some updates in time for hackathon 2, but may make further updates. This is an issue for holding those. It can just be a list

- [ ] not actually sure what features are needed

**Comment by RLC-DCPPC** [comment]
@mikedarcy , another one we need status on.

**Comment by mikedarcy** [comment]
This has been superseded by the implementation in described in https://github.com/nih-cfde/cfde-deriva/issues/334.

**Comment by ctb** [comment]
but wait - I think the implementation in #334 is about getting the information for what to retrieve, which is different from retrieving it.

we would still value having a command line tool to getting our hands on the data given the export format in #334. do we have a plan there?

**Comment by mikedarcy** [comment]
As far as I can recall, this issue was related to the prototype CLI tool that was initially designed to _import_ file metadata into Cavatica via their REST API  (which we are not doing anymore), and not actually resolve/retrieve files via manifest. This issue is pretty vague in any regard. We have kicked around the idea of having a tool to retrieve files, but we don't have an actual work plan to my knowledge. I recommend closing this and opening up a new issue that includes specifics and is coupled to an actual plan.

**Comment by ctb** [comment]
ok. will ask bob to discuss.
