### ISSUE TITLE
CFDE UI Landing Page

### ISSUE THREAD

**Issue by RLC-DCPPC** [nih-cfde/cfde-deriva#45]
This is important as a base for the dashboard (#23) and portal (#16) functionality

**Comment by RLC-DCPPC** [comment]
- [ ] - wireframe

**Comment by RLC-DCPPC** [comment]
@ACharbonneau , @jrchudy . Can we use this as the place to work on the next round of wireframes as discussed yesterday and ready for review next Tuesday?

The idea is that if we can take the 4Dn displays that we like, mark them up (or re-draw them) with the level 0 and level 1 categories that we expect in the catalog for June, then we'd have a better idea of what the UI would be for June and be able to show how the use cases would be executed using that UI.

**Comment by ACharbonneau** [comment]
So. the work for this is already started on https://github.com/nih-cfde/usecases/issues/5 but is currently focused on the interface proper...I think the current idea is that the landing page will be the plot from the proper interface (or possibly a reduced version of it) plus some other info, but we'll iron that out shortly

**Comment by carlkesselman** [comment]
I have given Bob the latest drafts of the GUDMAP landing page and “mega-menu”.  This may be of general interest.

----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Apr 22, 2020, 9:30 AM -0700, Amanda Charbonneau <notifications@github.com>, wrote:

So. the work for this is already started on nih-cfde/usecases#5<https://github.com/nih-cfde/usecases/issues/5> but is currently focused on the interface proper...I think the current idea is that the landing page will be the plot from the proper interface (or possibly a reduced version of it) plus some other info, but we'll iron that out shortly

**Comment by RLC-DCPPC** [comment]
![GUDMAP HOME DRAFT 16 APRIL 2020](https://user-images.githubusercontent.com/40363469/80111434-e342c000-854d-11ea-9b7e-6edc6b298df3.png)
![GUDMAP megamenu 2020-04-20 v2 CR](https://user-images.githubusercontent.com/40363469/80111452-e8077400-854d-11ea-8169-8e36c49eaccf.png)

**Comment by carlkesselman** [comment]
FYI… the first is the soon to be deployed GUDMAP landing page.  I thought this was interesting because there is some overlap between this and what Owen said he liked.  This page is the result of user testing that we did with Cia.

The second image is an example of a “mega-menu” which is the current goto approach for presenting rich, complex navigation.  Note that the page shown here is what pops up when you click the Browse Data item in the navigation bar.

Thanks

Carl


----------------------------------------------------------

Dr. Carl Kesselman
Dean’s Professor, Epstein Department of Industrial and Systems Engineering
Fellow, Information Sciences Institute Viterbi School of Engineering Professor,

Preventive Medicine Keck School of Medicine

University of Southern California
4676 Admiralty Way, Suite 1001, Marina del Rey, CA  90292-6695
Phone:  +1 (310) 448-9338
 Email:  carl@isi.edu
Web: http://www.isi.edu/~carl
On Apr 23, 2020, 7:34 AM -0700, Bob Carter <notifications@github.com>, wrote:

[GUDMAP HOME DRAFT 16 APRIL 2020]<https://user-images.githubusercontent.com/40363469/80111434-e342c000-854d-11ea-9b7e-6edc6b298df3.png>
[GUDMAP megamenu 2020-04-20 v2 CR]<https://user-images.githubusercontent.com/40363469/80111452-e8077400-854d-11ea-8169-8e36c49eaccf.png>

**Comment by jrchudy** [comment]
Use case 1, Researcher Browse and Filter:
https://drive.google.com/file/d/1pkyYDLba0SJTuda5-qzTgw3SSiI1p5cC/view?usp=sharing

Use case2, NIH Compare across DCCs:
https://drive.google.com/file/d/1jL1XbX-NWJ8T6Bwqy15GABMk6apqTJwA/view?usp=sharing

**Comment by ACharbonneau** [comment]
I'm not sure this is still an active issue per se. Closing in favor of more specific epics
