### ISSUE TITLE
Deliver a public CFDE interface sufficient for the DCCs to review reports and signoff on their data as presented by that interface. 

### ISSUE THREAD

**Issue by ACharbonneau** [nih-cfde/cfde-deriva#77]
This is the over-arching epic [discussed in this document](https://docs.google.com/document/d/1WV9Y2KR-tTXQlHxq7fDQztHvuK3DuLwh89-zVLi3JmY/edit#)

# User Story

As a DCC PI, I want to go to the CFDE portal and see a personalized dashboard interface where I can verify the data currently available for my DCC. 

To check whether all of my data tables were imported, I would like to see:
- How many data files exist for my DCC overall
- How many subjects are represented
- How many and which data types are represented
- How many and which anatomy terms are represented
- A list of Project names
- Number of biosamples in that Project
- Number of data_type in that Project

To check whether the relationships between my data points were correctly imported, I would like to be able to dynamically construct a handful of diagnostic queries that relate to the recent update. For example: List the file count for each unique value of assay_type by anatomy for new collection X

Since I expect changes to my data to occur from *either* my DCC submitting new information *or* updates to the CFDE model/infrastructure it is important that I be able to use either of these methods. 
- If I am constrained to *only* look at summary statistics, I will be unable to check for relational changes due to changes in the CFDE model or my own model
- If I am constrained to *only* do queries, I will be unable to do a holistic check for completeness, or to do a quick check that new data (with no model changes) was successfully integrated
- If I am constrained to only use pre-computed queries (rather than dynamic ones) I will be unable to test for relational changes in my data whenever either the CFDE or my own model adds or alters terms. I would need to request that the CFDE build new pre-computed queries, and for those changes to propagate through the infrastructure change management system before I could check my data

**Comment by ACharbonneau** [comment]
I'm gonna put a comment here

**Comment by lliming** [comment]
Stake-in-the-ground (holler if you disagree):

- DCCs are going to tell us who their authorized reviewers are for the Sep/Oct 2020 review.
- We will create a Globus group for the authorized reviewers for each DCC.
- We will add each authorized reviewer to their DCC's reviewer group.
- The portal will use group membership to know whether a logged-in individual is authorized to see a DCC's data for review.
- Remains TBD whether we will allow DCCs to administer their own groups at this time. (We don't have a nice CFDE-branded interface for it, so likely not?) That feature will be needed for other roadmap areas / planning statements, so it will happen eventually, but maybe not now.

If you don't think this isn't how it should be done, please speak up with an alternative ASAP, because we're otherwise ready to move on setting the groups up and asking DCCs to tell us who should be in their groups.

**Comment by RLC-DCPPC** [comment]
Are we ready to call this one done?

**Comment by ACharbonneau** [comment]
There are still open issues. They either need to be confirmed done, or moved to different epics.
