### ISSUE TITLE
Change portal display hints to track c2m2 changes

### ISSUE THREAD

**Issue by karlcz** [nih-cfde/cfde-deriva#97]
When we load a catalog with instance data using the revised c2m2, display hints customizing the Chaise portal presentation may also need adjustments where they rely on those aspects of c2m2.

**Comment by karlcz** [comment]
A test catalog at https://app-dev.nih-cfde.org/chaise/recordset/#6/CFDE:file  has current latest config and some test data. It needs further manual review to verify that facets definitions are working as expected.

A different dataset is needed to complete testing, since catalog 6 (HMP) lacks "collection" records and so cannot test collection-related functionality.

**Comment by jrchudy** [comment]
At first glance, the total number of records isn't the same (133,318 compared to 256,581 from before) which might be related to your comment:
> A different dataset is needed to complete testing

I also noticed there is a new facet available "Uncompressed Size in Bytes".
![image](https://user-images.githubusercontent.com/2932600/95784926-a3050480-0c89-11eb-9fd9-07cf370ec6c4.png)


For each facet:
 - Data Type
   - 8 instead of 16 from before
 - File Format
   - 13 instead of 24 from before
 - Assay Type
   - 17 instead of 22 from before
 - Anatomy
   - 42 instead of 118 from before
 - Subject Taxonomy
   - 1 instead of 90 from before
 - Common Fund Program
   - 1 instead of 7 from before
 - Project
   - facet options load, popup select dialog throws an error
   - old request:
      `
      https://app.nih-cfde.org/ermrest/catalog/1/attributegroup/T:=CFDE:file/(project,project_id_namespace)=(CFDE:project:id,id_namespace)/(id,id_namespace)=(CFDE:project_in_project_transitive:member_project_id,member_project_id_namespace)/M:=(leader_project_id,leader_project_id_namespace)=(CFDE:project:id,id_namespace)/F3:=left(RMB)=(public:ERMrest_Client:ID)/$M/F2:=left(RCB)=(public:ERMrest_Client:ID)/$M/F1:=left(id_namespace)=(CFDE:id_namespace:id)/$M/RID;M:=array_d(M:*),F3:=array_d(F3:*),F2:=array_d(F2:*),F1:=array_d(F1:*)@sort(RID)?limit=26
     `
   - new request:
     `
     https://app-dev.nih-cfde.org/ermrest/catalog/6/attributegroup/T:=CFDE:file/(project_id_namespace,project_local_id)=(CFDE:project:id_namespace,local_id)/(id_namespace,local_id)=(CFDE:project_in_project_transitive:member_project_id_namespace,member_project_local_id)/M:=(leader_project_id_namespace,leader_project_local_id)=(CFDE:project:id_namespace,local_id)/F3:=left(RMB)=(public:ERMrest_Client:ID)/$M/F2:=left(RCB)=(public:ERMrest_Client:ID)/$M/F1:=left(id_namespace)=(CFDE:id_namespace:id)/$M/RID;M:=array_d(M:*),F3:=array_d(F3:*),F2:=array_d(F2:*),F1:=array_d(F1:*)@sort(RID)?limit=26
     `
 - Subject Granularity
   - 1 instead of 8 from before
 - Subject Role
   - appears to be the same
 - File Creation Time
   - graph of data doesn't load
   - we send 2 requests to fetch the data, min/max request and binning request that relies on min/max data
   - min/max request return null for both values now
   - new request:
     `
     https://app-dev.nih-cfde.org/ermrest/catalog/6/aggregate/M:=CFDE:file/0:=min(creation_time),1:=max(creation_time)
     `
   - old request:
     `
      https://app.nih-cfde.org/ermrest/catalog/1/aggregate/M:=CFDE:file/0:=min(creation_time),1:=max(creation_time)
     `
 - Biosample Creation Time
   - same issue as "File Creation Time" facet with graph data
 - Size in Bytes
   - returned min/max values are different now
   - new values: min=32, max=71945973760
   - old values:   min=2, max=114383000000
 - Part of Collection
   - 0 instead of 2,605 from before
 - Described Biosample
   - 70,677 instead of 159,096 from before
   - rownames in facet are cleaner (shorter) now, not sure if that was intended
 - Described Subject
   - 2,409 instead of 48,967 from before
   - rownames in facet are cleaner (shorter) now, not sure if that was intended

**Comment by jrchudy** [comment]
Using catalog 12, the following was found:

For each facet:
 - Data Type
   - ~~8~~ 9 instead of 16 from before
 - File Format
   - ~~13~~ 16 instead of 24 from before
 - Assay Type
   - ~~17~~ 32 instead of 22 from before
 - Anatomy
   - ~~42~~ 87 instead of 118 from before
 - Subject Taxonomy
   - ~~1~~ 90 instead of 90 from before
   - NOTE: possibly consistent now
 - Common Fund Program
   - ~~1~~ 4 instead of 7 from before
 - Project
   - ~~facet options load, popup select dialog throws an error~~
   - 802 instead of 770 from before  
 - Subject Granularity
   - ~~1~~ 2 instead of 8 from before
 - Subject Role
   - appears to be the same (1 entry)
 - File Creation Time
   - ~~graph of data doesn't load~~ data loads now
   - same min, different max
 - Biosample Creation Time
   - ~~graph of data doesn't load~~ data loads now
   - different min/max
 - Size in Bytes
   - returned min/max values are different now
   - new values: min=32, max=93961109653
   - old values:   min=2, max=114383000000
 - Part of Collection
   - ~~0~~ 2,712 instead of 2,605 from before
 - Described Biosample
   - ~~70,677~~ 163,474 instead of 159,096 from before
   - rownames in facet are cleaner (shorter) now, not sure if that was intended
 - Described Subject
   - ~~2,409~~ 4,893 instead of 48,967 from before
   - rownames in facet are cleaner (shorter) now, not sure if that was intended

**Comment by karlcz** [comment]
Thanks, I am not seeing the query timeout now as I try to explore facets you mentioned.  The shortened row names were a mistake, where the column `id` got renamed to `local_id` and chaise had to fall back to just using the RID key instead because I forgot to update that row-name definition.
